<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#LaTeX-Custom-Commands" data-toc-modified-id="LaTeX-Custom-Commands-1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">1&nbsp;&nbsp;</span>LaTeX Custom Commands</a></span></li><li><span><a href="#Quantum-Error-Correction" data-toc-modified-id="Quantum-Error-Correction-2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2&nbsp;&nbsp;</span>Quantum Error Correction</a></span><ul class="toc-item"><li><span><a href="#Erasure-Correction-Using-3-Qutrit-Code" data-toc-modified-id="Erasure-Correction-Using-3-Qutrit-Code-2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Erasure Correction Using 3-Qutrit Code</a></span><ul class="toc-item"><li><span><a href="#Qutrit-State-Space" data-toc-modified-id="Qutrit-State-Space-2.1.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Qutrit State Space</a></span></li><li><span><a href="#n_qubit_basis-function-definition" data-toc-modified-id="n_qubit_basis-function-definition-2.1.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span><code>n_qubit_basis</code> function definition</a></span></li><li><span><a href="#3-Qutrit-State-Space" data-toc-modified-id="3-Qutrit-State-Space-2.1.3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>3-Qutrit State Space</a></span></li><li><span><a href="#tensor_basis-Function-For-Generating-Basis-States-of-N-n-qubit-State-Space" data-toc-modified-id="tensor_basis-Function-For-Generating-Basis-States-of-N-n-qubit-State-Space-2.1.4" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span><code>tensor_basis</code> Function For Generating Basis States of N n-qubit State Space</a></span></li><li><span><a href="#3-Qutrit-Erasure-Correction-Protocol" data-toc-modified-id="3-Qutrit-Erasure-Correction-Protocol-2.1.5" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.5&nbsp;&nbsp;</span>3-Qutrit Erasure Correction Protocol</a></span></li><li><span><a href="#random_normalized_coefs-function-definition" data-toc-modified-id="random_normalized_coefs-function-definition-2.1.6" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.6&nbsp;&nbsp;</span><code>random_normalized_coefs</code> function definition</a></span></li><li><span><a href="#Maximally-Mixed-Reduced-Density-Matrix" data-toc-modified-id="Maximally-Mixed-Reduced-Density-Matrix-2.1.7" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.7&nbsp;&nbsp;</span>Maximally Mixed Reduced Density Matrix</a></span></li><li><span><a href="#Qutrit-Code-Basis-States" data-toc-modified-id="Qutrit-Code-Basis-States-2.1.8" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.8&nbsp;&nbsp;</span>Qutrit Code Basis States</a></span></li><li><span><a href="#2-Qutrit-Unitary-Transformation" data-toc-modified-id="2-Qutrit-Unitary-Transformation-2.1.9" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.9&nbsp;&nbsp;</span>2-Qutrit Unitary Transformation</a></span></li></ul></li><li><span><a href="#Shor's-Nine-Qubit-Code" data-toc-modified-id="Shor's-Nine-Qubit-Code-2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Shor's Nine-Qubit Code</a></span><ul class="toc-item"><li><span><a href="#Utility-Functions" data-toc-modified-id="Utility-Functions-2.2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Utility Functions</a></span></li><li><span><a href="#Shor's-&quot;Check&quot;-Operators" data-toc-modified-id="Shor's-&quot;Check&quot;-Operators-2.2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Shor's "Check" Operators</a></span></li></ul></li></ul></li><li><span><a href="#CNOT-and-Error-Correction" data-toc-modified-id="CNOT-and-Error-Correction-3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">3&nbsp;&nbsp;</span>CNOT and Error Correction</a></span></li><li><span><a href="#Generate-Latex-Code-From-Qubit-State-Vector" data-toc-modified-id="Generate-Latex-Code-From-Qubit-State-Vector-4" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">4&nbsp;&nbsp;</span>Generate Latex Code From Qubit State Vector</a></span><ul class="toc-item"><li><span><a href="#Utility-Function-for-Converting-Complex-Numbers-to-Strings" data-toc-modified-id="Utility-Function-for-Converting-Complex-Numbers-to-Strings-4.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Utility Function for Converting Complex Numbers to Strings</a></span></li></ul></li><li><span><a href="#Sandbox" data-toc-modified-id="Sandbox-5" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">5&nbsp;&nbsp;</span>Sandbox</a></span></li></ul></div>

# LaTeX Custom Commands

$ \newcommand{\opexpect}[3]{\langle #1 \vert #2 \vert #3 \rangle} $
$ \newcommand{\rarrow}{\rightarrow} $
$ \newcommand{\bra}{\langle} $
$ \newcommand{\ket}{\rangle} $

$ \newcommand{\up}{\uparrow} $
$ \newcommand{\down}{\downarrow} $

$ \newcommand{\mb}[1]{\mathbf{#1}} $
$ \newcommand{\mc}[1]{\mathcal{#1}} $
$ \newcommand{\mbb}[1]{\mathbb{#1}} $
$ \newcommand{\mf}[1]{\mathfrak{#1}} $

$ \newcommand{\vect}[1]{\boldsymbol{\mathrm{#1}}} $
$ \newcommand{\expect}[1]{\langle #1\rangle} $

$ \newcommand{\innerp}[2]{\langle #1 \vert #2 \rangle} $
$ \newcommand{\fullbra}[1]{\langle #1 \vert} $
$ \newcommand{\fullket}[1]{\vert #1 \rangle} $
$ \newcommand{\supersc}[1]{^{\text{#1}}} $
$ \newcommand{\subsc}[1]{_{\text{#1}}} $
$ \newcommand{\sltwoc}{SL(2,\mathbb{C})} $
$ \newcommand{\sltwoz}{SL(2,\mathbb{Z})} $

$ \newcommand{\utilde}[1]{\underset{\sim}{#1}} $

# Quantum Error Correction

References: [ADH, 2014, Sec. 3](http://arxiv.org/abs/1411.7041) (& [CGL, 1999](http://arxiv.org/abs/quant-ph/9901025))

In [1]:
import matplotlib
matplotlib.use('qt5agg')
%matplotlib inline

In [63]:
# import IPython.display.Latex module for rendering LaTeX code in the notebook
from IPython.display import Latex

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

In [4]:
# gmpy2.digits() method is needed in function tensor_basis
import gmpy2

In [5]:
# qutip.visualization needed for functions _sequence_to_index and _index_to_sequence
import qutip.visualization as qvis

## Erasure Correction Using 3-Qutrit Code

Reference: ADH, 2014, Sec. 3.1

A 'qutrit' is a quantum state defined on a three-dimensional Hilbert space $\mc{H}_3$. A state $\fullket{\psi} \in \mc{H}_3$ can be written as:

$$ \fullket{\psi} = \sum_{i=0}^2 a_i \fullket{i} $$

where $ \fullket{i} \in \{\fullket{0}, \fullket{1}, \fullket{2}\}$

### Qutrit State Space

In QuTiP, a single qutrit state can be created as follows:

In [6]:
q0 = basis(3,0)
q1 = basis(3,1)
q2 = basis(3,2)

In [7]:
q0, q1, q2

(Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[1.]
  [0.]
  [0.]], Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[0.]
  [1.]
  [0.]], Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [1.]])

It will be more convenient to put these states into an numpy ndarray object

In [8]:
qutrit_basis = np.ndarray((3), dtype=Qobj)
qutrit_basis = [q0, q1, q2]

Create an alias with shorter name

In [9]:
qb = qutrit_basis

### `n_qubit_basis` function definition

In [10]:
def n_qubit_basis(n=2):
    '''returns a numpy array of Qobj elements, elements of which are basis state of Hilbert space of
    a n-qubit, where a n-qubit is a generalization of qubit (n=2), qutrit (n-3), etc. to arbitrary n'''

    if not isinstance(n,int) or n<=0:
        raise ValueError("Argument must positive non-zero integer")
    
    # The Hilbert space of an 'n-qubit' will be n-dimensional. A 1d array of length n will hold the basis states
    # of this Hilbert space.
    
    n_basis = np.ndarray((n),dtype=Qobj)
    
    for i in range(n):
        n_basis[i] = (basis(n,i))
        
    return n_basis

In [11]:
n_qubit_basis()

array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]],
       Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]], dtype=object)

In [12]:
n_qubit_basis(3)

array([Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]],
       Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]],
       Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]]], dtype=object)

### 3-Qutrit State Space

The three qutrit basis states can then be expressed as elements of a three-index array object

In [13]:
qutrit3_basis = np.ndarray((3,3,3), dtype=Qobj)
q3b = qutrit3_basis

In the following the array element `q3b[i][j][k]` contains the Qutip object for the state:
$$ \fullket{i} \otimes \fullket{j} \otimes \fullket{k} $$

In [14]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            q3b[i][j][k] = tensor([qb[i],qb[j],qb[k]])
            # or equivalently:
            # q3b[i][j][k] = ket([i,j,k],[3,3,3])

### `tensor_basis` Function For Generating Basis States of N n-qubit State Space

In [15]:
def tensor_basis(N=2,n=2):
    '''A n-qubit is generalization of qubit, qutrit etc. to arbitary n
    Give N such n-qubits, this function returns an numpy array whose elements
    are the basis states of the tensor product space of N n-qubits.'''
    
    if (not isinstance(n,int) or n<=1) or (not isinstance(N,int) or N<=1):
        raise ValueError("Both arguments must be positive integers greater than 1")
    
    # Create an array containing the basis states of a single n-qubit Hilbert space
    n_basis = n_qubit_basis(n)
    
#     tensor_basis = np.ndarray((n**N),dtype=Qobj)
#     t_basis = np.ndarray(tuple([n]*N), dtype=Qobj)
    t_basis = []
    
    format_str = "%0" + str(N) + "i"
#     print(format_str)
    indices = []
    y = []
    for i in range(n**N):
        x = format(format_str % int(gmpy2.digits(i,n)))
#         print(ket(x,dim=n))
#         print(x)
#         y = tuple(x)
#         t_basis[y] = ket(x,dim=n)
        t_basis.append(ket(x,dim=n))
    
    return t_basis

In [16]:
tensor_basis(2,2)

[Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[1.]
  [0.]
  [0.]
  [0.]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[0.]
  [1.]
  [0.]
  [0.]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [1.]
  [0.]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [1.]]]

### 3-Qutrit Erasure Correction Protocol

We can now create the particular combinations of the 3-qutrit states which will correspond to the basis states Alice uses to send her message

In [17]:
alice3_basis = np.ndarray(3, dtype=Qobj)
a3b = alice3_basis

In [18]:
a3b[0] = 1/(np.sqrt(3))*(q3b[0,0,0] + q3b[1,1,1] + q3b[2,2,2])
a3b[1] = 1/(np.sqrt(3))*(q3b[0,1,2] + q3b[1,2,0] + q3b[2,0,1])
a3b[2] = 1/(np.sqrt(3))*(q3b[0,2,1] + q3b[1,0,2] + q3b[2,1,0])

In [24]:
a3b[0]

Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[0.57735027]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.57735027]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.57735027]]

Construct state $\fullket{\tilde \psi}$ with random coefficients out of Alice's three-qutrit states.

In [25]:
a = np.ndarray((3))
dont_accept = True
while dont_accept:
    a[0] = np.random.random_sample()
    a[1] = np.random.random_sample()
    if (a[0]**2 + a[1]**2) < 1:
        dont_accept = False
a[2] = np.sqrt(1 - a[0]**2 - a[1]**2)
a

array([0.58729086, 0.3054668 , 0.7495195 ])

In [26]:
a[0]**2 + a[1]**2 + a[2]**2

0.9999999999999999

### `random_normalized_coefs` function definition

In [27]:
def random_normalized_coefs(N=3):
    '''Returns N floats, whose squared sum is 1'''
    a = np.ndarray((N))
    dont_accept = True
    sum = 0
    while dont_accept:
        for i in range(N-1):
            a[i] = np.random.random_sample()
            sum+= a[i]**2
        if sum < 1:
            dont_accept = False
    a[N-1] = np.sqrt(1 - sum)
    return a

In [28]:
a = random_normalized_coefs(len(a3b))

In [29]:
psi_3q = Qobj
for i in range(len(a3b)):
    psi_3q += a[i]*a3b[i]
psi_3q

/Users/deepak/miniconda3/envs/python3/lib/python3.6/site-packages/qutip/qobj.py:318: UserWarning: Initializing Qobj from unsupported type: <class 'type'>
  builtins.type(inpt))


Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[0.36386291]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.06351102]
 [0.        ]
 [0.44373806]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.44373806]
 [0.        ]
 [0.36386291]
 [0.        ]
 [0.06351102]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.06351102]
 [0.        ]
 [0.44373806]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.36386291]]

### Maximally Mixed Reduced Density Matrix

Tracing over any two qutrits yields a maximally mixed density-matrix. A maximally-mixed density matrix is a multiple of identity, i.e. all its eigenvalues are the same.

In [30]:
ket2dm(psi_3q).ptrace([0])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.33333333 0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.33333333]]

In [31]:
ket2dm(psi_3q).ptrace([1])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.33333333 0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.33333333]]

In [32]:
ket2dm(psi_3q).ptrace([2])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.33333333 0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.33333333]]

### Qutrit Code Basis States

Alice wishes to send the state $\fullket{\psi}$. For this purpose she uses the three-qutrit state:

$$ \fullket{\tilde \psi} = \sum_{i=0}^2 a_i \fullket{\tilde i} $$

where:

\begin{align}
    \fullket{\tilde 0} & = \frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{111} + \fullket{222} \right) \\
    \fullket{\tilde 1} & = \frac{1}{\sqrt{3}}\left( \fullket{012} + \fullket{120} + \fullket{201} \right) \\
    \fullket{\tilde 2} & = \frac{1}{\sqrt{3}}\left( \fullket{021} + \fullket{102} + \fullket{210} \right)
\end{align}

### 2-Qutrit Unitary Transformation

There exists a 2-qutrit unitary op $U_{12}$ whose action on any of the 3-qutrit basis states is given by:

$$ (U_{12} \otimes I_3) \fullket{\tilde i} = \fullket{i} \otimes \frac{1}{\sqrt{3}}(\fullket{00} + \fullket{11} + \fullket{22}) $$

where $\fullket{i}$ is a basis state of the single qutrit state space and $\fullket{\tilde i}$ is a state in Alice's erasure protocol.

The matrix $U_{12}$ acts on the first two qutrits by permuting their elements:

\begin{align*}
    \fullket{00} \rarrow \fullket{00}; \quad \fullket{11} \rarrow \fullket{01}; \quad \fullket{22} \rarrow \fullket{02} \\
    \fullket{01} \rarrow \fullket{12}; \quad \fullket{12} \rarrow \fullket{10}; \quad \fullket{20} \rarrow \fullket{11}
\end{align*}

Its action on the qutrit code basis states is given by:

\begin{align*}
(U_{12} \otimes I_3)\fullket{\tilde 0} & = (U_{12} \otimes I_3)\frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{111} + \fullket{222} \right) \\
& = \frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{011} + \fullket{022} \right) \\
& = \frac{1}{\sqrt{3}} \fullket{0} \otimes \left( \fullket{00} + \fullket{11} + \fullket{22} \right)
\end{align*}

Similarly:

\begin{align*}
(U_{12} \otimes I_3)\fullket{\tilde 1} & = \frac{1}{\sqrt{3}} \fullket{0} \otimes \left( \fullket{22} + \fullket{00} + \fullket{11} \right) \\
(U_{12} \otimes I_3)\fullket{\tilde 2} & = \frac{1}{\sqrt{3}} \fullket{1} \otimes \left( \fullket{11} + \fullket{22} + \fullket{00} \right) \\
\end{align*}

## Shor's Nine-Qubit Code

Reference: [Harlow & Hayden, 2013](http://arxiv.org/abs/1301.4504), [Shor, 1995](http://journals.aps.org/pra/abstract/10.1103/PhysRevA.52.R2493)

The 3 dimensional array ``q3b[ , , ]`` contains all the basis states of the 3-qutrit Hilbert space. In particular, ``q3b[0,0,0]`` and ``q3b[2,2,2]`` correspond to the states $\fullket{000}$ and $\fullket{222}$ respectively.

However, for Shor's error correction scheme, we need to work with **qubits** instead of **qutrits**!

For Shor's code we need the following two states:
$$ \fullket{\pm} = \frac{1}{2^{3/2}} \left( \fullket{000} \pm \fullket{111} \right)\left( \fullket{000} \pm \fullket{111} \right)\left( \fullket{000} \pm \fullket{111} \right) $$

In [33]:
down = basis(2,0)
up = basis(2,1)

In [34]:
qubit3_down = tensor([down,down,down])
qubit3_up = tensor([up,up,up])

In [35]:
qubit3plus = (qubit3_down + qubit3_up)*1/np.sqrt(2)
qubit3minus = (qubit3_down - qubit3_up)*1/np.sqrt(2)

In [36]:
shor_plus = tensor([qubit3plus,qubit3plus,qubit3plus])
shor_minus = tensor([qubit3minus,qubit3minus,qubit3minus])

In [37]:
shor_plus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[0.35355339]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.35355339]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.35355339]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.    

Define set of eight "check" operators:
$$ Z_1 Z_2, \quad Z_2 Z_3, \quad Z_4 Z_5, \quad Z_5 Z_6 \quad Z_7 Z_8 \quad Z_8 Z_9 $$
$$ X_1 X_2 X_3 X_4 X_5 X_6, \quad X_4 X_5 X_6 X_7 X_8 X_9 $$
where $ X_i, Z_i$ are the usual Pauli $\sigma_x, \sigma_z$ operators acting on the $i\supersc{th}$ site

### Utility Functions

Some utility functions, copied from 'Hubbard Model' notebook:

In [38]:
def identityList(N = 1,dims = 2):
    '''Returns a list of N identity operators for a N site spin-system with a
    Hilber space at each state of dimensionality dims 
    '''

    iden = identity(dims)
    
    iden_list = []

    [iden_list.append(iden) for i in range(N)]
    
    return iden_list

In [39]:
def posOperatorN(oper, i = 0, N = 1):
    '''Returns the operator given by oper, in the position representation, for the i^th site of an N site spin-chain
    with a Hilbert space, of dimension compatible with the dimension of the operator, at each site'''
    
    if not isinstance(oper, Qobj):
        raise TypeError('oper must of type qutip.Qobj')
    
    if not oper.isoper:
        raise ValueError('oper must be a qutip operator')
    
    shape = oper.shape

    if shape[0] == shape[1]:
        dims = shape[0]
    else:
        raise ValueError('oper must be a square matrix')
    
    if oper == identity(oper.shape[0]):
        return tensor(identityList(N,oper.shape[0]))
    else:
        iden_list = identityList(N, oper.shape[0])
        iden_list[i] = oper
        return tensor(iden_list)

In [40]:
def shorZCheckOp(m,n):
    '''Takes two integers m, n between 1 and 9 and returns tensor product operator corresponding to
    Z_m Z_n'''
    
    if not isinstance(m,int) or not isinstance(n,int):
        raise TypeError('From arguments must be of type integer')
    
    if m<1 or m>9 or n<1 or n>9:
        raise ValueError('Function takes two integers valued between 1 and 9')
        
    if m==n:
        raise ValueError('Arguments cannot be identical')
    
    # List of identity operators for 9 qubits
    oplist = identityList(9)
    oplist[m-1] = sigmaz()
    oplist[n-1] = sigmaz()
    
    return tensor(oplist)

### Shor's "Check" Operators

In [41]:
z12 = shorZCheckOp(1,2)
z23 = shorZCheckOp(2,3)
z45 = shorZCheckOp(4,5)
z56 = shorZCheckOp(5,6)
z78 = shorZCheckOp(7,8)
z89 = shorZCheckOp(8,9)

In [42]:
oplist = identityList(9)

for i in range(6):
    oplist[i] = sigmax()
    
x1to6 = tensor(oplist)

In [43]:
oplist = identityList(9)

for i in range(3,9):
    oplist[i] = sigmax()
    
x4to9 = tensor(oplist)

In [44]:
z12*shor_minus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0. 

In [45]:
shor_minus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0. 

In [46]:
shorCheckOpList = [z12,z23,z45,z56,z78,z89,x1to6,x4to9]

In [47]:
for op in shorCheckOpList:
#     print(op*shor_plus - shor_plus)
    if op*shor_plus == shor_plus:
        print("+1")
    if op*shor_minus == -1*shor_minus:
        print("-1")

+1
+1
+1
+1
+1
+1
+1
+1


In [48]:
x1 = posOperatorN(sigmax(),0,N=9)
x1

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2]], shape = (512, 512), type = oper, isherm = True
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [49]:
x1 * x4to9 == x4to9 * x1

True

In [50]:
for op in shorCheckOpList:
#     print(op*shor_plus - shor_plus)
    if x1*op == op*x1:
        print("True")
    else:
        print("False")

False
True
True
True
True
True
True
True


# CNOT and Error Correction

Mar 9, 2019

The CNOT gate can be used to generate the qutrit states required for Shor's repetition code. The code for quantum circuit visualization in the following was adapted from the `example-spin-chain-model.ipynb` notebook in the qutip examples by Anubhav Vardhan.

In [51]:
from qutip.qip.models.circuitprocessor import *

In [52]:
from qutip.qip.models.spinchain import *

In [53]:
N = 3

qc = QubitCircuit(N)

In [54]:
qc.png()

TypeError: 'Image' object is not callable

# Generate Latex Code From Qubit State Vector

In [55]:
def state_to_latex(qstate):
    '''Given a state in the form of a QuTiP ket as input (qstate), returns the latex expression for the
    state in terms of a superposition of basis states for the underlying Hilbert space. This method iterates
    through all the indices of the given state, uses the inbuilt function qvis._index_to_sequence to return the state
    corresponding to that index and then uses the inbuilt function qvis._sequence_to_latex to return the latex
    code for that state.
    
    
    Mar 16, 2019
    '''
    
    if (type(qstate) != qutip.qobj.Qobj):
        raise ValueError("Argument must be either a bra or a ket vector of type QObj")

    if not (qstate.isket or qstate.isbra):
        raise ValueError("Argument must be either a bra or a ket vector of type QObj")
    
    ket_flag = False
    bra_flag = False
    
    nonzero_index_list = []
    
    state_style = ""
    
    if qstate.isket:
        ket_flag = True
        num_states = qstate.shape[0]
        dim_list = qstate.dims[0]
        
        nonzero_index_list = qstate.data.nonzero()[0]
        
        state_style = 'ket'
        
    else:
        bra_flag = True
        num_states = qstate.shape[1]
        dim_list = qstate.dims[1]
        
        nonzero_index_list = qstate.data.nonzero()[1]
        
        state_style = 'bra'
        
    num_nonzero = len(nonzero_index_list)
        
    sequence_list = []
    
    coefs_list = []
    
    latex_code_list = []
        
    for i in range(num_nonzero):
        
        if ket_flag:
            
            coefs_list.append(qstate[nonzero_index_list[i]][0][0])
            
        elif bra_flag:
            
            coefs_list.append(qstate[0][0][nonzero_index_list[i]])
        
        seq = qvis._index_to_sequence(i, dim_list)
        
        sequence_list.append(seq)
        
        latex_code_list.append(qvis._sequence_to_latex(seq,style = state_style))
        
#     print(sequence_list)
    
#     print(latex_code_list)
    
#     print(coefs_list)
    
    return (coefs_list, latex_code_list)
        

## Utility Function for Converting Complex Numbers to Strings

In [56]:
def complex_to_str(cnum, sig_digits = (3,3), imag_unit = 'i'):
    '''
    Given a complex number as input, returns a string containing the real and imaginary parts rounded off
    to the number of significant digits specified in the sig_digits argument and with the imaginary unit
    being represented by the letter 'i' (insted of 'j' as in Python).
    '''
    
    if np.imag(cnum) != 0:
        return '({:.{}f}{:+.{}f}i)'.format(cnum.real, sig_digits[0], cnum.imag, sig_digits[1])
    else:
        return '{:.{}f}'.format(cnum.real, sig_digits[0])

In [57]:
import re

In [58]:
re.sub(r'^\$([^\$]*)\$$','\\1','$\\left|000\\right\\rangle$')

'\\left|000\\right\\rangle'

In [59]:
def consolidate_latex(qstate, sig_digits = 3):
    '''
    Takes the output of the state_to_latex() method, which consists of a list of tuples of the states
    with non-zero amplitudes. The first element of each tuple is the coefficient of the state and the
    second element is the LaTeX string representation of the state. This function takes this list, renders
    the coefficients to numbers to the precision given by sig_digits and returns the LaTeX string
    for the whole state.
    '''
    
    (coefs_list, tex_code_list) = state_to_latex(qstate)
    
    qstr = ''
    
    qstr += '$'
    
    for i in range(len(coefs_list)):
        qstr += complex_to_str(coefs_list[i]) + re.sub(r'^\$([^\$]*)\$$','\\1', tex_code_list[i]) + '+'
        
    # Remove extra '+' sign from the end
    
    qstr = qstr[0:-1]
        
    qstr += '$'
    
    return qstr

In [60]:
state_to_latex(psi_3q)

([(0.36386290901185475+0j),
  (0.06351102336887345+0j),
  (0.4437380608978708+0j),
  (0.4437380608978708+0j),
  (0.36386290901185475+0j),
  (0.06351102336887345+0j),
  (0.06351102336887345+0j),
  (0.4437380608978708+0j),
  (0.36386290901185475+0j)],
 ['$\\left|000\\right\\rangle$',
  '$\\left|001\\right\\rangle$',
  '$\\left|002\\right\\rangle$',
  '$\\left|010\\right\\rangle$',
  '$\\left|011\\right\\rangle$',
  '$\\left|012\\right\\rangle$',
  '$\\left|020\\right\\rangle$',
  '$\\left|021\\right\\rangle$',
  '$\\left|022\\right\\rangle$'])

In [61]:
consolidate_latex(psi_3q)

'$0.364\\left|000\\right\\rangle+0.064\\left|001\\right\\rangle+0.444\\left|002\\right\\rangle+0.444\\left|010\\right\\rangle+0.364\\left|011\\right\\rangle+0.064\\left|012\\right\\rangle+0.064\\left|020\\right\\rangle+0.444\\left|021\\right\\rangle+0.364\\left|022\\right\\rangle$'

In [62]:
Latex(_61)

NameError: name 'Latex' is not defined

# Sandbox

In [258]:
complex_to_str(2+0j)

'2.000+0.000j'

In [261]:
np.imag(2+0j) != 0

False

In [185]:
x = np.round(_180[0][0],3)
x

(0.227+0j)

In [197]:
len(_180[0])

9

In [187]:
type(_185)

numpy.complex128

In [188]:
type(1j)

complex

In [194]:
np.iscomplex(0j)

False

In [196]:
np.iscomplexobj(0j)

True

In [198]:
np.iscomplexobj(2)

False

In [200]:
np.imag(1j)

1.0

In [201]:
'.'+str(3)

'.3'

In [202]:
n = 3

In [210]:
m = 2

In [213]:
'{:{}.{}f}'.format(500,m,n)

'500.000'

In [215]:
f'{5:{m}.{n}f}'

'5.000'

In [227]:
'{} {:+}i'.format(x.real, x.imag)

'0.227 +0.0i'

In [234]:
x = 2 - 1j

In [243]:
'{:.{}f}{:+.{}f}i'.format(x.real, n, x.imag, n)

'2.000-1.000i'

In [220]:
np.sign?

In [49]:
print(psi_3q.data)

  (0, 0)	(0.22707449454814124+0j)
  (5, 0)	(0.4684907050014515+0j)
  (7, 0)	(0.2495735694865995+0j)
  (11, 0)	(0.2495735694865995+0j)
  (13, 0)	(0.22707449454814124+0j)
  (15, 0)	(0.4684907050014515+0j)
  (19, 0)	(0.4684907050014515+0j)
  (21, 0)	(0.2495735694865995+0j)
  (26, 0)	(0.22707449454814124+0j)


In [177]:
for i in state_to_latex(psi_3q):
#     print(i)
#     print(i[1])
    print(Latex(str(i[1])))

<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>
<IPython.core.display.Latex object>


In [167]:
from IPython.display import Latex

In [168]:
Latex('$\\left\\langle000\\right|$')

<IPython.core.display.Latex object>

In [50]:
format("%03s" % 2)

'  2'

In [51]:
N = 3
n = 3
format_str = "%0" + str(N) + "i"
indices = []
for i in range(n**N):
    x = format(format_str % int(gmpy2.digits(i,n)))
    indices.append(x)
indices

['000',
 '001',
 '002',
 '010',
 '011',
 '012',
 '020',
 '021',
 '022',
 '100',
 '101',
 '102',
 '110',
 '111',
 '112',
 '120',
 '121',
 '122',
 '200',
 '201',
 '202',
 '210',
 '211',
 '212',
 '220',
 '221',
 '222']

In [52]:
ket(indices[0],dim=3)

Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [53]:
np.random.permutation?

In [54]:
from itertools import combinations, permutations, combinations_with_replacement

In [55]:
for i in permutations([0,1,2]):
    print(i)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [56]:
for i in combinations_with_replacement([0,1,2],3):
    x = permutations(i)
    k1 = next(x)
    print(k1)
    k2 = next(x)
    while k2==k1:
        k2 = k1
        k1 = next(x)

(0, 0, 0)


StopIteration: 

In [58]:
x = permutations([0,1,2])

In [59]:
next(x)

(0, 1, 2)

In [ ]:
iter?

In [ ]:
gmpy2.digits?

In [60]:
tensor_basis(3,2)

[Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]],
 Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
 

In [61]:
ket2dm(psi_3q)

Quantum object: dims = [[3, 3, 3], [3, 3, 3]], shape = (27, 27), type = oper, isherm = True
Qobj data =
[[0.05156283 0.         0.         0.         0.         0.10638229
  0.         0.05667179 0.         0.         0.         0.05667179
  0.         0.05156283 0.         0.10638229 0.         0.
  0.         0.10638229 0.         0.05667179 0.         0.
  0.         0.         0.05156283]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.    

In [57]:
_84.ptrace([1,2])

NameError: name '_84' is not defined

In [ ]:
_84.eigenenergies()

In [62]:
import qutip.visualization as qvis

In [63]:
qutip.visualization._sequence_to_index([1,0,0],[2,2,2])

4

In [64]:
qvis._sequence_to_latex([1,0,1])

'$\\left|101\\right\\rangle$'

In [65]:
qvis._index_to_sequence(4,[3,3,3])

[0, 1, 1]

In [66]:
print(psi_3q.data)

  (0, 0)	(0.22707449454814124+0j)
  (5, 0)	(0.4684907050014515+0j)
  (7, 0)	(0.2495735694865995+0j)
  (11, 0)	(0.2495735694865995+0j)
  (13, 0)	(0.22707449454814124+0j)
  (15, 0)	(0.4684907050014515+0j)
  (19, 0)	(0.4684907050014515+0j)
  (21, 0)	(0.2495735694865995+0j)
  (26, 0)	(0.22707449454814124+0j)


In [115]:
psi_3q.dag().dims[1]

[3, 3, 3]

In [67]:
data = psi_3q.data

In [79]:
type(data)

qutip.fastsparse.fast_csr_matrix

In [88]:
psi_3q.full()[26][0]

(0.22707449454814124+0j)

In [89]:
type(_88)

numpy.complex128

In [86]:
_84.shape

(27, 1)

In [68]:
psi_3q.norm()

1.0

In [69]:
data

<27x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 9 stored elements in Compressed Sparse Row format>

In [70]:
psi_3q

Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[0.22707449]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.46849071]
 [0.        ]
 [0.24957357]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.24957357]
 [0.        ]
 [0.22707449]
 [0.        ]
 [0.46849071]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.46849071]
 [0.        ]
 [0.24957357]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.22707449]]

In [92]:
for i in psi_3q:
    print(i)

[[0.22707449+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.46849071+0.j]]
[[0.+0.j]]
[[0.24957357+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.24957357+0.j]]
[[0.+0.j]]
[[0.22707449+0.j]]
[[0.+0.j]]
[[0.46849071+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.46849071+0.j]]
[[0.+0.j]]
[[0.24957357+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.+0.j]]
[[0.22707449+0.j]]


TypeError: object of type 'Qobj' has no len()

In [ ]:
_107.shape

In [78]:
psi_3q[26][0][0]

(0.22707449454814124+0j)

In [96]:
type(psi_3q)

qutip.qobj.Qobj

In [101]:
psi_3q.dag().shape

(1, 27)

In [108]:
psi_3q.dag()[0][0][26]

(0.22707449454814124+0j)

In [125]:
psi_3q_data = psi_3q.data

In [149]:
non_zeros = psi_3q_data.nonzero()[0]
non_zeros

array([ 0,  5,  7, 11, 13, 15, 19, 21, 26], dtype=int32)

In [151]:
for i in non_zeros:
    print(psi_3q[i][0][0])

(0.22707449454814124+0j)
(0.4684907050014515+0j)
(0.2495735694865995+0j)
(0.2495735694865995+0j)
(0.22707449454814124+0j)
(0.4684907050014515+0j)
(0.4684907050014515+0j)
(0.2495735694865995+0j)
(0.22707449454814124+0j)


In [136]:
psi_3q.dag().data.nonzero()[1]

array([ 0,  5,  7, 11, 13, 15, 19, 21, 26], dtype=int32)

In [110]:
for i in psi_3q.dag():
    print(i)

[[0.22707449+0.j 0.        +0.j 0.        +0.j 0.        +0.j
  0.        +0.j 0.46849071+0.j 0.        +0.j 0.24957357+0.j
  0.        +0.j 0.        +0.j 0.        +0.j 0.24957357+0.j
  0.        +0.j 0.22707449+0.j 0.        +0.j 0.46849071+0.j
  0.        +0.j 0.        +0.j 0.        +0.j 0.46849071+0.j
  0.        +0.j 0.24957357+0.j 0.        +0.j 0.        +0.j
  0.        +0.j 0.        +0.j 0.22707449+0.j]]


In [111]:
_110.shape

NameError: name '_110' is not defined

In [160]:
type(_159)

IPython.core.display.Latex

In [272]:
def state_to_latex(qstate):
    '''Given a state in the form of a QuTiP ket as input (qstate), returns the latex expression for the
    state in terms of a superposition of basis states for the underlying Hilbert space. This method iterates
    through all the indices of the given state, uses the inbuilt function qvis._index_to_sequence to return the state
    corresponding to that index and then uses the inbuilt function qvis._sequence_to_latex to return the latex
    code for that state.
    '''
    
    if (type(qstate) != qutip.qobj.Qobj):
        raise ValueError("Argument must be either a bra or a ket vector of type QObj")

    if not (qstate.isket or qstate.isbra):
        raise ValueError("Argument must be either a bra or a ket vector of type QObj")
    
    ket_flag = False
    bra_flag = False
    
    nonzero_index_list = []
    
    state_style = ""
    
    if qstate.isket:
        ket_flag = True
        num_states = qstate.shape[0]
        dim_list = qstate.dims[0]
        
        nonzero_index_list = qstate.data.nonzero()[0]
        
        state_style = 'ket'
        
    else:
        bra_flag = True
        num_states = qstate.shape[1]
        dim_list = qstate.dims[1]
        
        nonzero_index_list = qstate.data.nonzero()[1]
        
        state_style = 'bra'
        
    num_nonzero = len(nonzero_index_list)
        
    sequence_list = []
    
    coefs_list = []
    
    latex_code_list = []
        
    for i in range(num_nonzero):
        
        if ket_flag:
            
            coefs_list.append(qstate[nonzero_index_list[i]][0][0])
            
        elif bra_flag:
            
            coefs_list.append(qstate[0][0][nonzero_index_list[i]])
        
        seq = qvis._index_to_sequence(i, dim_list)
        
        sequence_list.append(seq)
        
        latex_code_list.append(qvis._sequence_to_latex(seq,style = state_style))
        
#     print(sequence_list)
    
#     print(latex_code_list)
    
#     print(coefs_list)
    
    return zip(coefs_list, latex_code_list)
        

In [164]:
for i in state_to_latex(psi_3q):
    print(i)

((0.22707449454814124+0j), '$\\left|000\\right\\rangle$')
((0.4684907050014515+0j), '$\\left|001\\right\\rangle$')
((0.2495735694865995+0j), '$\\left|002\\right\\rangle$')
((0.2495735694865995+0j), '$\\left|010\\right\\rangle$')
((0.22707449454814124+0j), '$\\left|011\\right\\rangle$')
((0.4684907050014515+0j), '$\\left|012\\right\\rangle$')
((0.4684907050014515+0j), '$\\left|020\\right\\rangle$')
((0.2495735694865995+0j), '$\\left|021\\right\\rangle$')
((0.22707449454814124+0j), '$\\left|022\\right\\rangle$')


In [157]:
from IPython.display import Latex

In [159]:
Latex('$\\left\\langle000\\right|$')

<IPython.core.display.Latex object>

In [144]:
qvis._sequence_to_latex?

In [116]:
qvis._index_to_sequence?

In [ ]:
data.nonzero()

In [ ]:
type(_77)

In [ ]:
_77[0]

In [ ]:
data.data

In [ ]:
data.indptr

In [ ]:
data.indices

In [ ]:
data.todense()

In [ ]:
shape(_84)

In [ ]:
for i in data:
    print(i)

In [ ]:
data[5,0]

In [ ]:
l = [0,5,11,13]
kets = []
for i in range(len(l)):
    print (l[i])
    kets.append(ket(qvis._index_to_sequence(l[i],[3,3,3]),dim=3))

In [ ]:
kets;

In [ ]:
state = Qobj()
for i in range(len(l)):
    state = state + data[l[i],0]*kets[i]

In [ ]:
state

In [ ]:
print(state.data)

In [ ]:
psi_3q == state

In [ ]:
type(_94)

In [ ]:
ket(qvis._index_to_sequence(0,[3,3,3]),dim=3)

In [ ]:
ket?