<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#LaTeX-Custom-Commands" data-toc-modified-id="LaTeX-Custom-Commands-1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">1&nbsp;&nbsp;</span>LaTeX Custom Commands</a></span></li><li><span><a href="#Quantum-Error-Correction" data-toc-modified-id="Quantum-Error-Correction-2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2&nbsp;&nbsp;</span>Quantum Error Correction</a></span><ul class="toc-item"><li><span><a href="#Erasure-Correction-Using-3-Qutrit-Code" data-toc-modified-id="Erasure-Correction-Using-3-Qutrit-Code-2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Erasure Correction Using 3-Qutrit Code</a></span><ul class="toc-item"><li><span><a href="#Qutrit-State-Space" data-toc-modified-id="Qutrit-State-Space-2.1.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Qutrit State Space</a></span></li><li><span><a href="#n_qubit_basis-function-definition" data-toc-modified-id="n_qubit_basis-function-definition-2.1.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span><code>n_qubit_basis</code> function definition</a></span></li><li><span><a href="#3-Qutrit-State-Space" data-toc-modified-id="3-Qutrit-State-Space-2.1.3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>3-Qutrit State Space</a></span></li><li><span><a href="#tensor_basis-Function-For-Generating-Basis-States-of-N-n-qubit-State-Space" data-toc-modified-id="tensor_basis-Function-For-Generating-Basis-States-of-N-n-qubit-State-Space-2.1.4" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span><code>tensor_basis</code> Function For Generating Basis States of N n-qubit State Space</a></span></li><li><span><a href="#3-Qutrit-Erasure-Correction-Protocol" data-toc-modified-id="3-Qutrit-Erasure-Correction-Protocol-2.1.5" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.5&nbsp;&nbsp;</span>3-Qutrit Erasure Correction Protocol</a></span></li><li><span><a href="#random_normalized_coefs-function-definition" data-toc-modified-id="random_normalized_coefs-function-definition-2.1.6" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.6&nbsp;&nbsp;</span><code>random_normalized_coefs</code> function definition</a></span></li><li><span><a href="#Maximally-Mixed-Reduced-Density-Matrix" data-toc-modified-id="Maximally-Mixed-Reduced-Density-Matrix-2.1.7" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.7&nbsp;&nbsp;</span>Maximally Mixed Reduced Density Matrix</a></span></li><li><span><a href="#Qutrit-Code-Basis-States" data-toc-modified-id="Qutrit-Code-Basis-States-2.1.8" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.8&nbsp;&nbsp;</span>Qutrit Code Basis States</a></span></li><li><span><a href="#2-Qutrit-Unitary-Transformation" data-toc-modified-id="2-Qutrit-Unitary-Transformation-2.1.9" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1.9&nbsp;&nbsp;</span>2-Qutrit Unitary Transformation</a></span></li></ul></li><li><span><a href="#Shor's-Nine-Qubit-Code" data-toc-modified-id="Shor's-Nine-Qubit-Code-2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Shor's Nine-Qubit Code</a></span><ul class="toc-item"><li><span><a href="#Utility-Functions" data-toc-modified-id="Utility-Functions-2.2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Utility Functions</a></span></li><li><span><a href="#Shor's-&quot;Check&quot;-Operators" data-toc-modified-id="Shor's-&quot;Check&quot;-Operators-2.2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Shor's "Check" Operators</a></span></li></ul></li></ul></li><li><span><a href="#Sandbox" data-toc-modified-id="Sandbox-3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">3&nbsp;&nbsp;</span>Sandbox</a></span></li></ul></div>

# LaTeX Custom Commands

$ \newcommand{\opexpect}[3]{\langle #1 \vert #2 \vert #3 \rangle} $
$ \newcommand{\rarrow}{\rightarrow} $
$ \newcommand{\bra}{\langle} $
$ \newcommand{\ket}{\rangle} $

$ \newcommand{\up}{\uparrow} $
$ \newcommand{\down}{\downarrow} $

$ \newcommand{\mb}[1]{\mathbf{#1}} $
$ \newcommand{\mc}[1]{\mathcal{#1}} $
$ \newcommand{\mbb}[1]{\mathbb{#1}} $
$ \newcommand{\mf}[1]{\mathfrak{#1}} $

$ \newcommand{\vect}[1]{\boldsymbol{\mathrm{#1}}} $
$ \newcommand{\expect}[1]{\langle #1\rangle} $

$ \newcommand{\innerp}[2]{\langle #1 \vert #2 \rangle} $
$ \newcommand{\fullbra}[1]{\langle #1 \vert} $
$ \newcommand{\fullket}[1]{\vert #1 \rangle} $
$ \newcommand{\supersc}[1]{^{\text{#1}}} $
$ \newcommand{\subsc}[1]{_{\text{#1}}} $
$ \newcommand{\sltwoc}{SL(2,\mathbb{C})} $
$ \newcommand{\sltwoz}{SL(2,\mathbb{Z})} $

$ \newcommand{\utilde}[1]{\underset{\sim}{#1}} $

# Quantum Error Correction

References: [ADH, 2014, Sec. 3](http://arxiv.org/abs/1411.7041) (& [CGL, 1999](http://arxiv.org/abs/quant-ph/9901025))

In [1]:
import matplotlib
matplotlib.use('qt5agg')
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

In [4]:
# gmpy2.digits() method is needed in function tensor_basis
import gmpy2

In [5]:
# qutip.visualization needed for functions _sequence_to_index and _index_to_sequence
import qutip.visualization as qvis

## Erasure Correction Using 3-Qutrit Code

Reference: ADH, 2014, Sec. 3.1

A 'qutrit' is a quantum state defined on a three-dimensional Hilbert space $\mc{H}_3$. A state $\fullket{\psi} \in \mc{H}_3$ can be written as:

$$ \fullket{\psi} = \sum_{i=0}^2 a_i \fullket{i} $$

where $ \fullket{i} \in \{\fullket{0}, \fullket{1}, \fullket{2}\}$

### Qutrit State Space

In QuTiP, a single qutrit state can be created as follows:

In [6]:
q0 = basis(3,0)
q1 = basis(3,1)
q2 = basis(3,2)

In [7]:
q0, q1, q2

(Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[ 1.]
  [ 0.]
  [ 0.]], Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[ 0.]
  [ 1.]
  [ 0.]], Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
 Qobj data =
 [[ 0.]
  [ 0.]
  [ 1.]])

It will be more convenient to put these states into an numpy ndarray object

In [8]:
qutrit_basis = np.ndarray((3), dtype=Qobj)
qutrit_basis = [q0, q1, q2]

Create an alias with shorter name

In [9]:
qb = qutrit_basis

### `n_qubit_basis` function definition

In [10]:
def n_qubit_basis(n=2):
    '''returns a numpy array of Qobj elements, elements of which are basis state of Hilbert space of
    a n-qubit, where a n-qubit is a generalization of qubit (n=2), qutrit (n-3), etc. to arbitrary n'''

    if not isinstance(n,int) or n<=0:
        raise ValueError("Argument must positive non-zero integer")
    
    # The Hilbert space of an 'n-qubit' will be n-dimensional. A 1d array of length n will hold the basis states
    # of this Hilbert space.
    
    n_basis = np.ndarray((n),dtype=Qobj)
    
    for i in range(n):
        n_basis[i] = (basis(n,i))
        
    return n_basis

In [11]:
n_qubit_basis()

array([ Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 1.]
 [ 0.]],
       Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [ 1.]]], dtype=object)

In [12]:
n_qubit_basis(3)

array([ Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[ 1.]
 [ 0.]
 [ 0.]],
       Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[ 0.]
 [ 1.]
 [ 0.]],
       Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[ 0.]
 [ 0.]
 [ 1.]]], dtype=object)

### 3-Qutrit State Space

The three qutrit basis states can then be expressed as elements of a three-index array object

In [13]:
qutrit3_basis = np.ndarray((3,3,3), dtype=Qobj)
q3b = qutrit3_basis

In the following the array element `q3b[i][j][k]` contains the Qutip object for the state:
$$ \fullket{i} \otimes \fullket{j} \otimes \fullket{k} $$

In [14]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            q3b[i][j][k] = tensor([qb[i],qb[j],qb[k]])
            # or equivalently:
            # q3b[i][j][k] = ket([i,j,k],[3,3,3])

### `tensor_basis` Function For Generating Basis States of N n-qubit State Space

In [15]:
def tensor_basis(N=2,n=2):
    '''A n-qubit is generalization of qubit, qutrit etc. to arbitary n
    Give N such n-qubits, this function returns an numpy array whose elements
    are the basis states of the tensor product space of N n-qubits.'''
    
    if (not isinstance(n,int) or n<=1) or (not isinstance(N,int) or N<=1):
        raise ValueError("Both arguments must be positive integers greater than 1")
    
    # Create an array containing the basis states of a single n-qubit Hilbert space
    n_basis = n_qubit_basis(n)
    
#     tensor_basis = np.ndarray((n**N),dtype=Qobj)
    tensor_basis = np.ndarray(tuple([n]*N), dtype=Qobj)
    
    format_str = "%0" + str(N) + "i"
    indices = []
    y = []
    for i in range(n**N):
        x = format(format_str % int(gmpy2.digits(i,n)))
        y = tuple(x)
        tensor_basis[y] = ket(x,dim=n)
    
    return tensor_basis

In [19]:
tensor_basis = np.ndarray(tuple([2]*2), dtype=Qobj)
tensor_basis

array([[None, None],
       [None, None]], dtype=object)

In [16]:
tensor_basis()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### 3-Qutrit Erasure Correction Protocol

We can now create the particular combinations of the 3-qutrit states which will correspond to the basis states Alice uses to send her message

In [24]:
alice3_basis = np.ndarray(3, dtype=Qobj)
a3b = alice3_basis

In [25]:
a3b[0] = 1/(np.sqrt(3))*(q3b[0,0,0] + q3b[1,1,1] + q3b[2,2,2])
a3b[1] = 1/(np.sqrt(3))*(q3b[0,1,2] + q3b[1,2,0] + q3b[2,0,1])
a3b[2] = 1/(np.sqrt(3))*(q3b[0,2,1] + q3b[1,0,2] + q3b[2,1,0])

Construct state $\fullket{\tilde \psi}$ with random coefficients out of Alice's three-qutrit states.

In [26]:
a = np.ndarray((3))
dont_accept = True
while dont_accept:
    a[0] = np.random.random_sample()
    a[1] = np.random.random_sample()
    if (a[0]**2 + a[1]**2) < 1:
        dont_accept = False
a[2] = np.sqrt(1 - a[0]**2 - a[1]**2)
a

array([ 0.2285364 ,  0.67156164,  0.70482343])

In [27]:
a[0]**2 + a[1]**2 + a[2]**2

1.0

### `random_normalized_coefs` function definition

In [28]:
def random_normalized_coefs(N=3):
    '''Returns N floats, whose squared sum is 1'''
    a = np.ndarray((N))
    dont_accept = True
    sum = 0
    while dont_accept:
        for i in range(N-1):
            a[i] = np.random.random_sample()
            sum+= a[i]**2
        if sum < 1:
            dont_accept = False
    a[N-1] = np.sqrt(1 - sum)
    return a

In [29]:
a = random_normalized_coefs(len(a3b))
psi_3q = Qobj
for i in range(len(a3b)):
    psi_3q += a[i]*a3b[i]
psi_3q

/Users/deepak/miniconda3/lib/python3.6/site-packages/qutip/qobj.py:305: UserWarning: Initializing Qobj from unsupported type: <class 'type'>
  builtins.type(inpt))


Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[ 0.08694723]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.34974207]
 [ 0.        ]
 [ 0.45105875]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.45105875]
 [ 0.        ]
 [ 0.08694723]
 [ 0.        ]
 [ 0.34974207]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.34974207]
 [ 0.        ]
 [ 0.45105875]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.08694723]]

### Maximally Mixed Reduced Density Matrix

Tracing over any two qutrits yields a maximally mixed density-matrix. A maximally-mixed density matrix is a multiple of identity, i.e. all its eigenvalues are the same.

In [30]:
ket2dm(psi_3q).ptrace([0])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[ 0.33333333  0.          0.        ]
 [ 0.          0.33333333  0.        ]
 [ 0.          0.          0.33333333]]

In [31]:
ket2dm(psi_3q).ptrace([1])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[ 0.33333333  0.          0.        ]
 [ 0.          0.33333333  0.        ]
 [ 0.          0.          0.33333333]]

In [32]:
ket2dm(psi_3q).ptrace([2])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[ 0.33333333  0.          0.        ]
 [ 0.          0.33333333  0.        ]
 [ 0.          0.          0.33333333]]

### Qutrit Code Basis States

Alice wishes to send the state $\fullket{\psi}$. For this purpose she uses the three-qutrit state:

$$ \fullket{\tilde \psi} = \sum_{i=0}^2 a_i \fullket{\tilde i} $$

where:

\begin{align}
    \fullket{\tilde 0} & = \frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{111} + \fullket{222} \right) \\
    \fullket{\tilde 1} & = \frac{1}{\sqrt{3}}\left( \fullket{012} + \fullket{120} + \fullket{201} \right) \\
    \fullket{\tilde 2} & = \frac{1}{\sqrt{3}}\left( \fullket{021} + \fullket{102} + \fullket{210} \right)
\end{align}

### 2-Qutrit Unitary Transformation

There exists a 2-qutrit unitary op $U_{12}$ whose action on any of the 3-qutrit basis states is given by:

$$ (U_{12} \otimes I_3) \fullket{\tilde i} = \fullket{i} \otimes \frac{1}{\sqrt{3}}(\fullket{00} + \fullket{11} + \fullket{22}) $$

where $\fullket{i}$ is a basis state of the single qutrit state space and $\fullket{\tilde i}$ is a state in Alice's erasure protocol.

The matrix $U_{12}$ acts on the first two qutrits by permuting their elements:

\begin{align*}
    \fullket{00} \rarrow \fullket{00}; \quad \fullket{11} \rarrow \fullket{01}; \quad \fullket{22} \rarrow \fullket{02} \\
    \fullket{01} \rarrow \fullket{12}; \quad \fullket{12} \rarrow \fullket{10}; \quad \fullket{20} \rarrow \fullket{11}
\end{align*}

Its action on the qutrit code basis states is given by:

\begin{align*}
(U_{12} \otimes I_3)\fullket{\tilde 0} & = (U_{12} \otimes I_3)\frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{111} + \fullket{222} \right) \\
& = \frac{1}{\sqrt{3}}\left( \fullket{000} + \fullket{011} + \fullket{022} \right) \\
& = \frac{1}{\sqrt{3}} \fullket{0} \otimes \left( \fullket{00} + \fullket{11} + \fullket{22} \right)
\end{align*}

Similarly:

\begin{align*}
(U_{12} \otimes I_3)\fullket{\tilde 1} & = \frac{1}{\sqrt{3}} \fullket{0} \otimes \left( \fullket{22} + \fullket{00} + \fullket{11} \right) \\
(U_{12} \otimes I_3)\fullket{\tilde 2} & = \frac{1}{\sqrt{3}} \fullket{1} \otimes \left( \fullket{11} + \fullket{22} + \fullket{00} \right) \\
\end{align*}

## Shor's Nine-Qubit Code

Reference: [Harlow & Hayden, 2013](http://arxiv.org/abs/1301.4504), [Shor, 1995](http://journals.aps.org/pra/abstract/10.1103/PhysRevA.52.R2493)

The 3 dimensional array ``q3b[ , , ]`` contains all the basis states of the 3-qutrit Hilbert space. In particular, ``q3b[0,0,0]`` and ``q3b[2,2,2]`` correspond to the states $\fullket{000}$ and $\fullket{222}$ respectively.

However, for Shor's error correction scheme, we need to work with **qubits** instead of **qutrits**!

For Shor's code we need the following two states:
$$ \fullket{\pm} = \frac{1}{2^{3/2}} \left( \fullket{000} \pm \fullket{111} \right)\left( \fullket{000} \pm \fullket{111} \right)\left( \fullket{000} \pm \fullket{111} \right) $$

In [33]:
down = basis(2,0)
up = basis(2,1)

In [34]:
qubit3_down = tensor([down,down,down])
qubit3_up = tensor([up,up,up])

In [35]:
qubit3plus = (qubit3_down + qubit3_up)*1/np.sqrt(2)
qubit3minus = (qubit3_down - qubit3_up)*1/np.sqrt(2)

In [36]:
shor_plus = tensor([qubit3plus,qubit3plus,qubit3plus])
shor_minus = tensor([qubit3minus,qubit3minus,qubit3minus])

In [37]:
shor_plus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.35355339]
 [ 0.        ]
 [ 0. 

Define set of eight "check" operators:
$$ Z_1 Z_2, \quad Z_2 Z_3, \quad Z_4 Z_5, \quad Z_5 Z_6 \quad Z_7 Z_8 \quad Z_8 Z_9 $$
$$ X_1 X_2 X_3 X_4 X_5 X_6, \quad X_4 X_5 X_6 X_7 X_8 X_9 $$
where $ X_i, Z_i$ are the usual Pauli $\sigma_x, \sigma_z$ operators acting on the $i\supersc{th}$ site

### Utility Functions

Some utility functions, copied from 'Hubbard Model' notebook:

In [38]:
def identityList(N = 1,dims = 2):
    '''Returns a list of N identity operators for a N site spin-system with a
    Hilber space at each state of dimensionality dims 
    '''

    iden = identity(dims)
    
    iden_list = []

    [iden_list.append(iden) for i in range(N)]
    
    return iden_list

In [39]:
def posOperatorN(oper, i = 0, N = 1):
    '''Returns the operator given by oper, in the position representation, for the i^th site of an N site spin-chain
    with a Hilbert space, of dimension compatible with the dimension of the operator, at each site'''
    
    if not isinstance(oper, Qobj):
        raise TypeError('oper must of type qutip.Qobj')
    
    if not oper.isoper:
        raise ValueError('oper must be a qutip operator')
    
    shape = oper.shape

    if shape[0] == shape[1]:
        dims = shape[0]
    else:
        raise ValueError('oper must be a square matrix')
    
    if oper == identity(oper.shape[0]):
        return tensor(identityList(N,oper.shape[0]))
    else:
        iden_list = identityList(N, oper.shape[0])
        iden_list[i] = oper
        return tensor(iden_list)

In [40]:
def shorZCheckOp(m,n):
    '''Takes two integers m, n between 1 and 9 and returns tensor product operator corresponding to
    Z_m Z_n'''
    
    if not isinstance(m,int) or not isinstance(n,int):
        raise TypeError('From arguments must be of type integer')
    
    if m<1 or m>9 or n<1 or n>9:
        raise ValueError('Function takes two integers valued between 1 and 9')
        
    if m==n:
        raise ValueError('Arguments cannot be identical')
    
    # List of identity operators for 9 qubits
    oplist = identityList(9)
    oplist[m-1] = sigmaz()
    oplist[n-1] = sigmaz()
    
    return tensor(oplist)

### Shor's "Check" Operators

In [41]:
z12 = shorZCheckOp(1,2)
z23 = shorZCheckOp(2,3)
z45 = shorZCheckOp(4,5)
z56 = shorZCheckOp(5,6)
z78 = shorZCheckOp(7,8)
z89 = shorZCheckOp(8,9)

In [42]:
oplist = identityList(9)

for i in range(6):
    oplist[i] = sigmax()
    
x1to6 = tensor(oplist)

In [43]:
oplist = identityList(9)

for i in range(3,9):
    oplist[i] = sigmax()
    
x4to9 = tensor(oplist)

In [44]:
z12*shor_minus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0. 

In [45]:
shor_minus

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (512, 1), type = ket
Qobj data =
[[ 0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.35355339]
 [ 0.        ]
 [ 0. 

In [46]:
shorCheckOpList = [z12,z23,z45,z56,z78,z89,x1to6,x4to9]

In [47]:
for op in shorCheckOpList:
#     print(op*shor_plus - shor_plus)
    if op*shor_plus == shor_plus:
        print("+1")
    if op*shor_minus == -1*shor_minus:
        print("-1")

+1
+1
+1
+1
+1
+1
+1
+1


In [48]:
x1 = posOperatorN(sigmax(),0,N=9)
x1

Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2]], shape = (512, 512), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]

In [49]:
x1 * x4to9 == x4to9 * x1

True

In [50]:
for op in shorCheckOpList:
#     print(op*shor_plus - shor_plus)
    if x1*op == op*x1:
        print("True")
    else:
        print("False")

False
True
True
True
True
True
True
True


# Sandbox

In [51]:
print(psi_3q.data)

  (0, 0)	(0.0869472309429+0j)
  (5, 0)	(0.349742072217+0j)
  (7, 0)	(0.451058749262+0j)
  (11, 0)	(0.451058749262+0j)
  (13, 0)	(0.0869472309429+0j)
  (15, 0)	(0.349742072217+0j)
  (19, 0)	(0.349742072217+0j)
  (21, 0)	(0.451058749262+0j)
  (26, 0)	(0.0869472309429+0j)


In [52]:
format("%03s" % 2)

'  2'

In [53]:
N = 3
n = 3
format_str = "%0" + str(N) + "i"
indices = []
for i in range(n**N):
    x = format(format_str % int(g2.digits(i,n)))
    indices.append(x)
indices

NameError: name 'g2' is not defined

In [54]:
ket(indices[0],dim=3)

IndexError: list index out of range

In [55]:
np.random.permutation?

In [56]:
from itertools import combinations, permutations, combinations_with_replacement

In [57]:
for i in permutations([0,1,2]):
    print(i)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [58]:
for i in combinations_with_replacement([0,1,2],3):
    x = permutations(i)
    k1 = next(x)
    print(k1)
    k2 = next(x)
    while k2==k1:
        k2 = k1
        k1 = next(x)

(0, 0, 0)


StopIteration: 

In [59]:
x = permutations([0,1,2])

In [60]:
next(x)

(0, 1, 2)

In [61]:
iter?

In [62]:
g2.digits?

Object `g2.digits` not found.


In [63]:
tensor_basis(3,2)

TypeError: 'numpy.ndarray' object is not callable

In [64]:
ket2dm(psi_3q)

Quantum object: dims = [[3, 3, 3], [3, 3, 3]], shape = (27, 27), type = oper, isherm = True
Qobj data =
[[ 0.00755982  0.          0.          0.          0.          0.0304091
   0.          0.03921831  0.          0.          0.          0.03921831
   0.          0.00755982  0.          0.0304091   0.          0.          0.
   0.0304091   0.          0.03921831  0.          0.          0.          0.
   0.00755982]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.      

In [66]:
_64.ptrace([1,2])

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 0.00755982  0.          0.          0.          0.          0.0304091
   0.          0.03921831  0.        ]
 [ 0.          0.12231952  0.          0.15775422  0.          0.          0.
   0.          0.0304091 ]
 [ 0.          0.          0.203454    0.          0.03921831  0.
   0.15775422  0.          0.        ]
 [ 0.          0.15775422  0.          0.203454    0.          0.          0.
   0.          0.03921831]
 [ 0.          0.          0.03921831  0.          0.00755982  0.
   0.0304091   0.          0.        ]
 [ 0.0304091   0.          0.          0.          0.          0.12231952
   0.          0.15775422  0.        ]
 [ 0.          0.          0.15775422  0.          0.0304091   0.
   0.12231952  0.          0.        ]
 [ 0.03921831  0.          0.          0.          0.          0.15775422
   0.          0.203454    0.        ]
 [ 0.          0.0304091   0.          0.

In [67]:
_64.eigenenergies()

array([ -1.01976881e-016,  -3.47387885e-018,  -2.14477108e-019,
        -5.42034371e-033,  -5.42878849e-034,  -3.07458882e-034,
        -1.96908619e-050,  -1.06910588e-050,  -3.35804599e-065,
        -1.24988075e-066,  -4.75400250e-067,  -9.48809087e-082,
        -9.54002186e-115,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   1.40126292e-083,   8.00786169e-069,
         2.65202850e-050,   4.90582563e-050,   4.05164233e-049,
         3.62988196e-034,   7.39793149e-034,   1.23025263e-033,
         4.23082921e-018,   2.07697664e-017,   1.00000000e+000])

In [68]:
import qutip.visualization as qvis

In [69]:
qutip.visualization._sequence_to_index([1,0,0],[2,2,2])

4

In [70]:
qvis._sequence_to_latex([1,0,1])

'$\\left|101\\right\\rangle$'

In [71]:
qvis._index_to_sequence(27,[3,3,3])

[0, 0, 0]

In [72]:
print(psi_3q.data)

  (0, 0)	(0.0869472309429+0j)
  (5, 0)	(0.349742072217+0j)
  (7, 0)	(0.451058749262+0j)
  (11, 0)	(0.451058749262+0j)
  (13, 0)	(0.0869472309429+0j)
  (15, 0)	(0.349742072217+0j)
  (19, 0)	(0.349742072217+0j)
  (21, 0)	(0.451058749262+0j)
  (26, 0)	(0.0869472309429+0j)


In [73]:
data = psi_3q.data

In [74]:
psi_3q.norm()

1.0000000000000002

In [75]:
data

<27x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 9 stored elements in Compressed Sparse Row format>

In [76]:
def ket_to_latex(qket):
    '''Given a state in the form of a QuTiP ket as input (qket), returns the latex expression for the
    state in terms of a superposition of basis states for the underlying Hilbert space'''
    
    return

In [77]:
data.nonzero()

(array([ 0,  5,  7, 11, 13, 15, 19, 21, 26], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [79]:
type(_77)

tuple

In [80]:
_77[0]

array([ 0,  5,  7, 11, 13, 15, 19, 21, 26], dtype=int32)

In [81]:
data.data

array([ 0.08694723+0.j,  0.34974207+0.j,  0.45105875+0.j,  0.45105875+0.j,
        0.08694723+0.j,  0.34974207+0.j,  0.34974207+0.j,  0.45105875+0.j,
        0.08694723+0.j])

In [82]:
data.indptr

array([0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 8,
       8, 8, 8, 8, 9], dtype=int32)

In [83]:
data.indices

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [84]:
data.todense()

matrix([[ 0.08694723+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.34974207+0.j],
        [ 0.00000000+0.j],
        [ 0.45105875+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.45105875+0.j],
        [ 0.00000000+0.j],
        [ 0.08694723+0.j],
        [ 0.00000000+0.j],
        [ 0.34974207+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.34974207+0.j],
        [ 0.00000000+0.j],
        [ 0.45105875+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.00000000+0.j],
        [ 0.08694723+0.j]])

In [86]:
shape(_84)

(27, 1)

In [87]:
for i in data:
    print(i)

  (0, 0)	(0.0869472309429+0j)




  (0, 0)	(0.349742072217+0j)

  (0, 0)	(0.451058749262+0j)



  (0, 0)	(0.451058749262+0j)

  (0, 0)	(0.0869472309429+0j)

  (0, 0)	(0.349742072217+0j)



  (0, 0)	(0.349742072217+0j)

  (0, 0)	(0.451058749262+0j)




  (0, 0)	(0.0869472309429+0j)


In [88]:
data[5,0]

(0.3497420722169694+0j)

In [89]:
l = [0,5,11,13]
kets = []
for i in range(len(l)):
    print (l[i])
    kets.append(ket(qvis._index_to_sequence(l[i],[3,3,3]),dim=3))

0
5
11
13


In [90]:
kets;

In [91]:
state = Qobj()
for i in range(len(l)):
    state = state + data[l[i],0]*kets[i]

In [92]:
state

Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[ 0.08694723]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.34974207]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.45105875]
 [ 0.        ]
 [ 0.08694723]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]

In [93]:
print(state.data)

  (0, 0)	(0.0869472309429+0j)
  (5, 0)	(0.349742072217+0j)
  (11, 0)	(0.451058749262+0j)
  (13, 0)	(0.0869472309429+0j)


In [94]:
psi_3q == state

False

In [96]:
type(_94)

bool

In [97]:
ket(qvis._index_to_sequence(0,[3,3,3]),dim=3)

Quantum object: dims = [[3, 3, 3], [1, 1, 1]], shape = (27, 1), type = ket
Qobj data =
[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]

In [98]:
ket?